# Site settings
title: KishPatel.com
email: contact@kishpatel.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Kish, and I'm a designer from London, UK. I love to leverage software and human interaction to build better experiences for consumers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kishpatel.com" # the base hostname & protocol for your site
twitter_username: TheKishPatel
github_username:  TheKishPatel
permalink: "/:title"


# Build settings
markdown: kramdown
